# This workflow will install Python dependencies, run tests and lint with a single version of Python
# Additionally a .exe file is being created, downloadable from artifacts
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Build Cross-Platform Game

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pyinstaller pygame-ce
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      shell: bash

    - name: Build with PyInstaller
      shell: bash
      run: |
        if [ "${{ matrix.os }}" == "windows-latest" ]; then
          python -m PyInstaller --onefile --noconsole --icon="assets/icon.png" --add-data "assets;assets" game.py
        elif [ "${{ matrix.os }}" == "macos-latest" ]; then
          python -m PyInstaller --onefile --noconsole --add-data "assets:assets" game.py
        else
          python -m PyInstaller --onefile --noconsole --add-data "assets:assets" game.py
        fi

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        # create a unique name for each artifact based on the OS
        name: game-${{ matrix.os }}
        path: |
          dist/*.exe
          dist/game
          dist/game.app
